FROM quay.io/jupyterhub/jupyterhub:latest 
 
RUN pip install \
 dockerspawner \
 jupyterhub-firstuseauthenticator \
 jhub_remote_user_authenticator \
 jupyterhub-idle-culler \
# jhub_shibboleth_auth \
 oauthenticator \
 jupyterhub-idle-culler